### ISSUE TITLE
"Invalid Host Header"

### ISSUE THREAD

**Issue by AnubhutiRoX** [jbt/docker#112]
Similar to issue [#301.](https://github.com/maputnik/editor/issues/301). I thought this is the right place to report the issue. When I deploy my app in docker from local, I am able to see its up and running on localhost:. When I try to deploy it on kubernetes environment, it returns invalid host header on browser, even though the pod is in running state.

I am using React>17 and nx for microfront end.

docker file is -

build environment
FROM node:14.18.1-buster-slim
ARG APPNAME

WORKDIR /home/${APPNAME}
COPY package.json package.json

RUN npm install --registry=
RUN npm i -g @nrwl/cli --registry=
COPY . ./

Building Specific app
RUN echo ${APPNAME}

RUN nx build ${APPNAME}

RUN groupadd -g 10000 10000 &&
useradd -u 10000 -g 10000 -m -d /home/${APPNAME} -s /bin/bash 10000 &&
mkdir -p /opt/dummy/logs &&
chown -R 10000:10000 /opt

EXPOSE 4200

CMD nx serve ${APPNAME} --host=0.0.0.0 --disableHostCheck

**Comment by jbt** [comment]
Hey @AnubhutiRoX - I'm afraid this isn't the right place for Docker the container technology. This docker is a different thing, it's a documentation tool (which at this point is quite old and unmaintained).

You probably need something over on https://github.com/docker for the other Docker!
