### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jaydunning** [jbt/docker#81]
Can you please clarify your intent regarding licensing? Is docker's lack of a license intentional, or an oversight?

**Comment by jbt** [comment]
Pure oversight on my part, I'm afraid - I've been very bad at maintaining this and it's been neglected a bit unfortunately :(

I think MIT or ISC fits best with how I sort of assumed I'd licensed it. I'll clarify that and add a proper license file.

**Comment by joatmon** [comment]
+1

I'd really like to use docker, but my company's lawyers won't let me touch anything that doesn't have an explicit license.
