### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by alinex** [jbt/docker#99]
Hopefully not! I want to get the 1.0.0 version out and help extending it. But if no one cares here maybe I have to think about doing it all myself.

If I have to do it myself maybe I will do a complete rewrite of everything, getting it in my own world of thinking. Features I would go on for are:

- more HTML features
- more layout control
- mermaid / plantuml integration
- and lots more

Let me know if the work here goes on.

**Comment by jbt** [comment]
Yup, I've been absolutely terrible and let this slide. I was hoping to round off #86 (the long-standing 1.0.0 PR) finished and off alpha a few days ago but I got quite ill and didn't manage to get onto it. I'll be rounding that off this weekend hopefully.

That said, I'm more than happy to let someone take the reins for keeping this maintained going forward. I sadly have very little time for side-projects like this these days so if someone can do a better job of it than me then I'm up for that.

**Comment by alinex** [comment]
Ok, I don't know if I am the correct one to takeover because I mostly do my things in coffeescript. But at first I will have a deeper look and will contribute to it.

**Comment by alinex** [comment]
After further looks and thinking about my documentation i came to slightly other main features like docker. 
Also i wanted to try to make a documentation solution my way i started a quick and successfull test package. This has become one of my github packages and works fine so far. Not really finished i will use this in future. But my own solution is in some way opinionated and at least for now specialized for me so for the grest majority yours is the better tool and because i used docker more than a year now i will try to make it a brother project and bring new things from my own also to you.

If you need more information look at the first document results under http://alinex.github.io/node-codedoc which will improve over the next days further. The main changes are:
- doc only from block comments
- comments and code displayed below each other
- natural ordered file tree
- markdown-it extended for graphical display like UML diagrams
- responsiv design with templates

More to come every day, please have a look and give me your opinion.
